name: CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - 6-push-to-otax

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SSH to server and pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/www/speksi
            git pull
            chmod -R 755 .
